name: glacier-app
dependencies:
  - pip
  - pyviz::param
  - pyviz::pyviz_comms
  - pyviz::datashader
  - bokeh::bokeh
  - pyviz::holoviews
  - pyviz::geoviews
  - pyviz::panel=0.6.2
  - conda-forge::pytables
  - pip:
    - jupyter-panel-proxy
